# Generated by Django 2.1.15 on 2022-01-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinquiry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
