# Generated by Django 4.0.1 on 2022-01-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='some_value', max_length=120)),
                ('description', models.CharField(default='some_value', max_length=120)),
                ('target_price', models.DecimalField(decimal_places=2, default='some_value', max_digits=1000)),
            ],
        ),
    ]
